version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: finance-account
    depends_on:
      - db
    links:
      - "db:database"
    ports:
      - target: 3000
        host_ip: 127.0.0.1
        published: "3000"
        protocol: tcp
        mode: host
    build: .

  migration:
    image: finance-account:latest
    command: ["npm", "run", "migrate"]
    links: 
      - db
    depends_on:
      - db

