version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: finance-account
    depends_on:
      - db
    links:
      - "db:database"
    ports:
      - "8080:8080"
      - "5000:5000"
    build: .
    volumes:
      - './:/app'
      - '/app/node_modules'

  migration:
    image: finance-account:latest
    command: ["npm", "run", "migrate"]
    links: 
      - db
    depends_on:
      - db

