apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: migration
  name: migration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migration
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: migration
    spec:
      containers:
        - args:
            - npm
            - run
            - migrate
          image: finance-account:latest
          name: migration
          resources: {}
      restartPolicy: Always
status: {}
